### ISSUE TITLE
Facing issue Python and its module version 

### ISSUE THREAD

**Issue by freaktechz** [joxeankoret/multiav#2]
Hi Jox

Can you provide me compatible python and its module version details 

I tried 2.6.6 , 2.7.9 and 3.4.3

Keep on throwing some errors

Traceback (most recent call last):
  File "multiav.py", line 500, in <module>
    main(sys.argv[1])
  File "multiav.py", line 487, in main
    ret = multi_av.scan(path, AV_SPEED_ALL)
  File "multiav.py", line 448, in scan
    return self.single_scan(path, max_speed)
  File "multiav.py", line 453, in single_scan
    results = self.scan_one(av_engine, path, results, max_speed)
  File "multiav.py", line 462, in scan_one
    av.scan(path)
  File "multiav.py", line 113, in scan
    output = check_output(cmd)
  File "/usr/local/lib/python2.7/subprocess.py", line 530, in check_output
    process = Popen(stdout=PIPE, _popenargs, *_kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 672, in **init**
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1201, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by joxeankoret** [comment]
Uhm... I think you're not using it right. It works with any 2.7 Python version. From the back-trace, it seems that either you are missing one AV that you have enabled or you don't have the right path to it.

**Comment by freaktechz** [comment]
Thanks for reply Jox , Let me go through again :)
