### ISSUE TITLE
runing test script - problem

### ISSUE THREAD

**Issue by h4d12** [joxeankoret/multiav#26]
hello , and thank you for your work about multiav.
i setup this tool on ubuntu
python setup.py install

then for test i run the expamle code here 
https://github.com/joxeankoret/multiav/blob/master/multiav/scripts/multiav-scan.py
and set the multiav.CMultiAV() to my config file in the example code below, i enable just E-sacn in config file ( all other have flag Disable=1) , but when i run the test code i get this errors : 

`Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/multiav/core.py", line 638, in scan_one
    av.scan(path)
  File "/usr/local/lib/python2.7/dist-packages/multiav/core.py", line 153, in scan
    call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
**OSError: [Errno 2] No such file or directory**
{}
`
please help me :)
best regards

**Comment by VikramGhosh1992** [comment]
Hello,
I got the bellow as output:

<multiav.core.CMultiAV object at 0x0000028C8F07A0A0>

**How can I find the readable scanned data. Please help?**

I have used your script as bellow:

import configparser
import os
import sys
import json
import multiav
import pprint
from multiav.core import CMultiAV, AV_SPEED_MEDIUM,AV_SPEED_FAST

multi_av = CMultiAV("C:/Users/vikra/Desktop/multiav-master/multiav-master/multiav/config.cfg")
ret = multi_av.scan("knowpw.py", multiav.core.AV_SPEED_FAST)
pprint.pprint(multi_av)
